/**
 * HealthWise AI — Seeded Official WHO Knowledge Base
 *
 * Pre-indexed, official WHO Fact Sheets for core public health topics.
 * Ensures the knowledge base is grounded with authentic WHO information
 * out of the box in demo mode, and serves as baseline for synchronization.
 */

import { KnowledgeDocument, KnowledgeChunk } from '../../types/database';

const WHO_SOURCE_ID = '00000000-0000-0000-0000-000000000001';

export const SEEDED_WHO_DOCUMENTS: KnowledgeDocument[] = [
  {
    id: 'doc-who-dengue',
    source_id: WHO_SOURCE_ID,
    external_id: '12d077de-803a-4179-b2e8-d9055f05f470',
    condition_name: 'Dengue (break-bone fever)',
    title: 'Dengue and Severe Dengue',
    topic: 'Dengue',
    disease_category: 'vector_borne',
    summary: 'Dengue is a mosquito-borne viral infection transmitted by Aedes mosquitoes. While most infections cause mild flu-like illness, severe dengue is a potentially fatal complication involving plasma leaking, fluid accumulation, respiratory distress, or severe bleeding.',
    full_content: 'Dengue is a viral infection caused by the dengue virus (DENV), transmitted through bites of infected Aedes aegypti mosquitoes. Symptoms include high fever, severe headache, retro-orbital pain, muscle and joint pains, nausea, vomiting, and rash. Prevention relies on vector control, eliminating standing water, and using mosquito repellent.',
    source_url: 'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue',
    publication_date: '2025-08-21',
    last_modified_date: '2026-01-12T18:11:32Z',
    last_verified_date: '2026-01-12',
    last_synchronized_date: '2026-01-12T18:11:32Z',
    language: 'en',
    version: '1.0',
    checksum: 'h_who_dengue_v1',
    status: 'published',
    verification_status: 'verified',
    reviewer: 'WHO Department of Control of Neglected Tropical Diseases',
    tags: ['who-verified', 'dengue', 'mosquito-borne', 'tropical-disease', 'vector-control'],
    created_at: '2025-08-21T00:00:00Z',
    updated_at: '2026-01-12T18:11:32Z',
  },
  {
    id: 'doc-who-diabetes',
    source_id: WHO_SOURCE_ID,
    external_id: 'who-factsheet-diabetes-001',
    condition_name: 'Diabetes Mellitus',
    title: 'Diabetes',
    topic: 'Diabetes',
    disease_category: 'noncommunicable_disease',
    summary: 'Diabetes is a chronic disease that occurs when the pancreas does not produce enough insulin or when the body cannot effectively use the insulin it produces. Type 2 diabetes is largely preventable through lifestyle intervention.',
    full_content: 'Diabetes is a major cause of blindness, kidney failure, heart attacks, stroke and lower limb amputation. Healthy diet, regular physical activity, maintaining normal body weight, and avoiding tobacco use are ways to prevent or delay the onset of type 2 diabetes.',
    source_url: 'https://www.who.int/news-room/fact-sheets/detail/diabetes',
    publication_date: '2024-11-14',
    last_modified_date: '2025-06-10T12:00:00Z',
    last_verified_date: '2025-06-10',
    last_synchronized_date: '2025-06-10T12:00:00Z',
    language: 'en',
    version: '1.0',
    checksum: 'h_who_diabetes_v1',
    status: 'published',
    verification_status: 'verified',
    reviewer: 'WHO Department of Noncommunicable Diseases',
    tags: ['who-verified', 'diabetes', 'chronic-disease', 'nutrition', 'lifestyle'],
    created_at: '2024-11-14T00:00:00Z',
    updated_at: '2025-06-10T12:00:00Z',
  },
  {
    id: 'doc-who-hypertension',
    source_id: WHO_SOURCE_ID,
    external_id: 'who-factsheet-hypertension-001',
    condition_name: 'Hypertension (High Blood Pressure)',
    title: 'Hypertension',
    topic: 'Hypertension',
    disease_category: 'cardiovascular_disease',
    summary: 'Hypertension (high blood pressure) is when the pressure in your blood vessels is too high (140/90 mmHg or higher). It is common but can be serious if not treated. An estimated 1.28 billion adults aged 30–79 years worldwide have hypertension.',
    full_content: 'Many people with hypertension do not notice any symptoms. Very high blood pressure can cause headaches, blurred vision, chest pain and other symptoms. Lifestyle modifications such as reducing salt intake, eating more fruit and vegetables, and being active help lower blood pressure.',
    source_url: 'https://www.who.int/news-room/fact-sheets/detail/hypertension',
    publication_date: '2024-03-16',
    last_modified_date: '2025-05-18T10:00:00Z',
    last_verified_date: '2025-05-18',
    last_synchronized_date: '2025-05-18T10:00:00Z',
    language: 'en',
    version: '1.0',
    checksum: 'h_who_hypertension_v1',
    status: 'published',
    verification_status: 'verified',
    reviewer: 'WHO Cardiovascular Diseases Team',
    tags: ['who-verified', 'hypertension', 'blood-pressure', 'cardiovascular', 'heart-health'],
    created_at: '2024-03-16T00:00:00Z',
    updated_at: '2025-05-18T10:00:00Z',
  },
  {
    id: 'doc-who-malaria',
    source_id: WHO_SOURCE_ID,
    external_id: 'who-factsheet-malaria-001',
    condition_name: 'Malaria',
    title: 'Malaria',
    topic: 'Malaria',
    disease_category: 'vector_borne',
    summary: 'Malaria is a life-threatening disease caused by Plasmodium parasites spread to people through the bites of infected female Anopheles mosquitoes. It is preventable and curable.',
    full_content: 'In 2022, there were an estimated 249 million cases of malaria and 608,000 malaria deaths worldwide. Early symptoms include fever, chills, headache, and fatigue. Vector control through insecticide-treated mosquito nets and indoor residual spraying is the main way to prevent malaria.',
    source_url: 'https://www.who.int/news-room/fact-sheets/detail/malaria',
    publication_date: '2024-12-04',
    last_modified_date: '2025-04-15T09:30:00Z',
    last_verified_date: '2025-04-15',
    last_synchronized_date: '2025-04-15T09:30:00Z',
    language: 'en',
    version: '1.0',
    checksum: 'h_who_malaria_v1',
    status: 'published',
    verification_status: 'verified',
    reviewer: 'WHO Global Malaria Programme',
    tags: ['who-verified', 'malaria', 'parasitic-infection', 'mosquito-borne', 'prevention'],
    created_at: '2024-12-04T00:00:00Z',
    updated_at: '2025-04-15T09:30:00Z',
  },
  {
    id: 'doc-who-vaccines',
    source_id: WHO_SOURCE_ID,
    external_id: 'who-factsheet-vaccines-001',
    condition_name: 'Immunization & Vaccination',
    title: 'Vaccines and Immunization',
    topic: 'Vaccination',
    disease_category: 'preventive_health',
    summary: 'Immunization is a global health and development success story, saving an estimated 3.5–5 million lives every year from diseases like diphtheria, tetanus, pertussis, influenza and measles.',
    full_content: 'Vaccines train your immune system to create antibodies, just as it does when it is exposed to a disease. However, because vaccines contain only killed or weakened forms of germs like viruses or bacteria, they do not cause the disease or put you at risk of its complications.',
    source_url: 'https://www.who.int/news-room/fact-sheets/detail/immunization-coverage',
    publication_date: '2024-07-15',
    last_modified_date: '2025-07-10T14:20:00Z',
    last_verified_date: '2025-07-10',
    last_synchronized_date: '2025-07-10T14:20:00Z',
    language: 'en',
    version: '1.0',
    checksum: 'h_who_vaccines_v1',
    status: 'published',
    verification_status: 'verified',
    reviewer: 'WHO Department of Immunization, Vaccines and Biologicals',
    tags: ['who-verified', 'vaccination', 'immunization', 'prevention', 'public-health'],
    created_at: '2024-07-15T00:00:00Z',
    updated_at: '2025-07-10T14:20:00Z',
  },
];

export const SEEDED_WHO_CHUNKS: KnowledgeChunk[] = [
  // --- DENGUE CHUNKS ---
  {
    id: 'chunk-dengue-1',
    document_id: 'doc-who-dengue',
    chunk_index: 0,
    heading: 'Executive Summary',
    topic: 'Dengue',
    content: 'Dengue and Severe Dengue — Executive Summary: Dengue is a mosquito-borne viral infection transmitted by Aedes mosquitoes. While most infections cause mild flu-like illness, severe dengue is a potentially fatal complication involving plasma leaking, fluid accumulation, respiratory distress, or severe bleeding.',
    tags: ['dengue', 'summary', 'vector-borne'],
    token_count: 55,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue' },
    created_at: '2025-08-21T00:00:00Z',
  },
  {
    id: 'chunk-dengue-2',
    document_id: 'doc-who-dengue',
    chunk_index: 1,
    heading: 'Symptoms & Warning Signs',
    topic: 'Dengue',
    content: '### Dengue: Symptoms & Warning Signs\nMost people who get dengue do not have symptoms. For those who do, symptoms usually begin 4–10 days after infection and last for 2–7 days:\n- Sudden high fever (40°C/104°F)\n- Severe headache and pain behind the eyes (retro-orbital pain)\n- Muscle and joint pains ("break-bone fever")\n- Nausea, vomiting, and swollen glands\n- Skin rash appearing 2–5 days after fever onset.\nSevere dengue warning signs occur after the fever drops (days 3–7): severe abdominal pain, persistent vomiting, rapid breathing, bleeding gums or nose, blood in vomit or stool, fatigue, restlessness, and pale cold skin. People with warning signs need immediate emergency hospital care.',
    tags: ['dengue', 'symptoms', 'warning-signs', 'fever', 'joint-pain'],
    token_count: 152,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue', section: 'symptoms' },
    created_at: '2025-08-21T00:00:00Z',
  },
  {
    id: 'chunk-dengue-3',
    document_id: 'doc-who-dengue',
    chunk_index: 2,
    heading: 'Prevention & Vector Control',
    topic: 'Dengue',
    content: '### Dengue: Prevention & Control\nThe mosquitoes that spread dengue (Aedes aegypti) bite primarily during the day.\nTo lower infection risk:\n- Wear clothing that covers as much of the body as possible (light-colored, long sleeves and pants)\n- Apply mosquito repellent containing DEET, Picaridin, or IR3535 to exposed skin\n- Use window and door screens, vaporizers, and bed nets\n- Eliminate mosquito breeding sites: cover, empty, and clean domestic water containers, flower pots, and tires on a weekly basis to eliminate standing water.',
    tags: ['dengue', 'prevention', 'vector-control', 'mosquito-bites'],
    token_count: 110,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue', section: 'prevention' },
    created_at: '2025-08-21T00:00:00Z',
  },
  {
    id: 'chunk-dengue-4',
    document_id: 'doc-who-dengue',
    chunk_index: 3,
    heading: 'Diagnostics & Supportive Care',
    topic: 'Dengue',
    content: '### Dengue: Diagnostics & Care\nThere is no specific antiviral treatment for dengue. Management focuses on pain relief and supportive care:\n- Use acetaminophen (paracetamol) for pain and fever\n- CRITICAL WARNING: Avoid non-steroidal anti-inflammatory medicines (NSAIDs) such as ibuprofen and aspirin, because they thin the blood and significantly increase the risk of hemorrhage/bleeding\n- Drink plenty of liquids (oral rehydration salts, water, clean fluids) to prevent dehydration\n- Seek hospital admission immediately if severe dengue warning signs appear.',
    tags: ['dengue', 'treatment', 'paracetamol', 'avoid-ibuprofen', 'care'],
    token_count: 120,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue', section: 'treatment' },
    created_at: '2025-08-21T00:00:00Z',
  },

  // --- DIABETES CHUNKS ---
  {
    id: 'chunk-diabetes-1',
    document_id: 'doc-who-diabetes',
    chunk_index: 0,
    heading: 'Symptoms & Early Detection',
    topic: 'Diabetes',
    content: '### Diabetes: Symptoms & Early Warning Signs\nSymptoms of type 2 diabetes may occur suddenly or develop gradually over years:\n- Feeling more thirsty than usual (polydipsia)\n- Frequent urination, especially at night (polyuria)\n- Losing weight without trying\n- Feeling tired and weak\n- Blurred vision and slow-healing sores or frequent infections\n- Numbness or tingling in the hands or feet.\nMany people with type 2 diabetes have no early symptoms, which is why regular blood glucose screening is vital, especially for adults over 35 or those with risk factors.',
    tags: ['diabetes', 'symptoms', 'blood-sugar', 'thirst', 'urination'],
    token_count: 125,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/diabetes', section: 'symptoms' },
    created_at: '2024-11-14T00:00:00Z',
  },
  {
    id: 'chunk-diabetes-2',
    document_id: 'doc-who-diabetes',
    chunk_index: 1,
    heading: 'Prevention & Lifestyle Management',
    topic: 'Diabetes',
    content: '### Diabetes: Prevention & Healthy Habits\nType 2 diabetes can be prevented or delayed through effective lifestyle choices:\n- Maintain healthy body weight (BMI 18.5–24.9)\n- Engage in at least 150 minutes of moderate-intensity physical activity (brisk walking, cycling, swimming) per week\n- Eat a healthy diet: prioritize dietary fiber, whole grains, vegetables, and fruit; minimize saturated fats, refined sugar, and ultra-processed food\n- Avoid tobacco smoking, which increases the risk of diabetes and cardiovascular complications\n- Undergo periodic blood sugar testing (fasting glucose, HbA1c).',
    tags: ['diabetes', 'prevention', 'diet', 'exercise', 'lifestyle'],
    token_count: 130,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/diabetes', section: 'prevention' },
    created_at: '2024-11-14T00:00:00Z',
  },

  // --- HYPERTENSION CHUNKS ---
  {
    id: 'chunk-hypertension-1',
    document_id: 'doc-who-hypertension',
    chunk_index: 0,
    heading: 'Symptoms & Risk Factors',
    topic: 'Hypertension',
    content: '### Hypertension: The Silent Killer\nHypertension is defined as persistent blood pressure of 140/90 mmHg or higher.\nMost people with hypertension have no warning symptoms at all, which is why it is called the "silent killer."\nWhen symptoms do occur, they may include early morning headaches, nosebleeds, irregular heart rhythms, vision changes, and buzzing in the ears.\nSevere hypertension can cause fatigue, nausea, vomiting, confusion, anxiety, chest pain, and muscle tremors. Measuring blood pressure is the only way to know if you have hypertension.',
    tags: ['hypertension', 'blood-pressure', 'symptoms', 'silent-killer'],
    token_count: 118,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/hypertension', section: 'symptoms' },
    created_at: '2024-03-16T00:00:00Z',
  },
  {
    id: 'chunk-hypertension-2',
    document_id: 'doc-who-hypertension',
    chunk_index: 1,
    heading: 'Prevention & Non-Pharmacological Management',
    topic: 'Hypertension',
    content: '### Hypertension: Prevention & Dietary Interventions\nLifestyle modifications can prevent and control high blood pressure:\n- Reduce salt/sodium intake to less than 2,000 mg of sodium (equivalent to 5 g of salt / 1 teaspoon) per day\n- Consume more potassium-rich foods (fruits and vegetables)\n- Follow the DASH dietary pattern (Dietary Approaches to Stop Hypertension)\n- Be physically active: at least 150 minutes of moderate aerobic exercise weekly\n- Maintain a healthy weight (each 1 kg weight loss reduces blood pressure by ~1 mmHg)\n- Limit alcohol consumption and completely avoid tobacco smoking.',
    tags: ['hypertension', 'prevention', 'salt-reduction', 'dash-diet', 'lifestyle'],
    token_count: 135,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/hypertension', section: 'prevention' },
    created_at: '2024-03-16T00:00:00Z',
  },

  // --- MALARIA CHUNKS ---
  {
    id: 'chunk-malaria-1',
    document_id: 'doc-who-malaria',
    chunk_index: 0,
    heading: 'Symptoms & Diagnosis',
    topic: 'Malaria',
    content: '### Malaria: Symptoms & Warning Signs\nMalaria is caused by Plasmodium parasites transmitted through bites of infected female Anopheles mosquitoes.\nSymptoms usually appear 10–15 days after the infective mosquito bite:\n- Initial symptoms: high fever, shaking chills, severe headache, muscle aches, and fatigue\n- Gastrointestinal symptoms: nausea, vomiting, and diarrhea\n- Children with severe malaria frequently develop severe anemia, respiratory distress, or cerebral malaria with seizures and coma.\nAny acute fever in a malaria-endemic area should be investigated immediately with rapid diagnostic tests (RDTs) or microscopy.',
    tags: ['malaria', 'symptoms', 'fever', 'chills', 'anopheles'],
    token_count: 125,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/malaria', section: 'symptoms' },
    created_at: '2024-12-04T00:00:00Z',
  },
  {
    id: 'chunk-malaria-2',
    document_id: 'doc-who-malaria',
    chunk_index: 1,
    heading: 'Prevention & Control',
    topic: 'Malaria',
    content: '### Malaria: Prevention Strategies\nMalaria is both preventable and curable:\n- Sleeping under insecticide-treated nets (ITNs) provides effective personal protection\n- Indoor residual spraying (IRS) with insecticides on indoor walls\n- Chemoprevention: antimalarial tablets (chemoprophylaxis) for travelers and seasonal malaria chemoprevention (SMC) for children in high-transmission areas\n- WHO-recommended malaria vaccines (RTS,S/AS01 and R21/Matrix-M) for children living in regions with moderate-to-high transmission.',
    tags: ['malaria', 'prevention', 'bed-nets', 'vaccine', 'chemoprevention'],
    token_count: 110,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/malaria', section: 'prevention' },
    created_at: '2024-12-04T00:00:00Z',
  },

  // --- VACCINE CHUNKS ---
  {
    id: 'chunk-vaccine-1',
    document_id: 'doc-who-vaccines',
    chunk_index: 0,
    heading: 'How Vaccines Work & Safety',
    topic: 'Vaccination',
    content: '### Vaccines: Mechanism & Scientific Safety\nVaccines protect people against disease by working with their body\'s natural defenses to build protection.\n- When you get a vaccine, your immune system recognizes the invading germ, produces antibodies, and remembers the germ to destroy it quickly if exposed in the future.\n- Vaccines contain only killed or weakened forms of viruses or bacteria (or fragments like mRNA/proteins), meaning they do not cause the disease.\n- Rigorous multi-stage clinical trials test vaccines for safety and efficacy before approval, followed by continuous global safety monitoring.\nVaccination protects both the individual and the wider community through herd immunity.',
    tags: ['vaccination', 'safety', 'immunity', 'antibodies', 'science'],
    token_count: 135,
    metadata: { source_url: 'https://www.who.int/news-room/fact-sheets/detail/immunization-coverage', section: 'safety' },
    created_at: '2024-07-15T00:00:00Z',
  },
];
